import {
  Product,
  Client,
  Consignment,
  Visit,
  ExchangeNote,
  Quote,
  Order,
  InventoryMovement,
  SaleTransaction,
  AppSettings,
  ClientInventoryItem,
} from './types';

import { CATALOG_PRODUCTS } from './data/catalogProducts';

export const INITIAL_PRODUCTS: Product[] = CATALOG_PRODUCTS.map((p, idx) => ({
  id: `prod-cat-${idx + 1}`,
  name: p.name || 'Produto RN 3D',
  sku: p.sku || `SKU-${idx + 1}`,
  category: p.category || 'Case de Munição',
  isKeychain: p.category === 'Fidgets' || p.category === 'Chaveiro',
  description: p.description || '',
  storageCapacity: p.storageCapacity || '',
  material: 'PLA',
  color: 'Preto / Personalizado',
  weightGram: 50,
  lengthMm: 100,
  widthMm: 50,
  heightMm: 40,
  avgPrintTimeMinutes: 60,
  batchQuantity: 5,
  estimatedCost: 8.0,
  standardPrice: p.standardPrice !== undefined ? p.standardPrice : (p.category === 'Chaveiro' ? 6.0 : (p.category === 'Case de Munição' ? 45.0 : 25.0)),
  cashPrice: p.cashPrice !== undefined ? p.cashPrice : (p.category === 'Chaveiro' || p.isKeychain ? 4.0 : (p.standardPrice ?? 25.0)),
  minPrice: 20.0,
  suggestedRetailPrice: p.category === 'Case de Munição' ? 80.0 : 45.0,
  currentStock: 20,
  minStock: 5,
  allowsCustomization: true,
  customizationOptions: { name: true, logo: true, color: true, text: true, other: false },
  status: 'Ativo',
  monthlySalesCount: 0,
  turnoverRatePct: 0,
  daysWithoutMovement: 0,
}));

export const INITIAL_CLIENTS: Client[] = [
  {
    id: 'cli-1',
    name: 'Depósito Avenida',
    fantasyName: 'Depósito Avenida Bebidas',
    document: '12.345.678/0001-90',
    responsible: 'Carlos Henrique',
    phone: '(21) 98765-4321',
    whatsapp: '5521987654321',
    email: 'deposito.avenida@gmail.com',
    cep: '26210-000',
    street: 'Avenida Governador Amaral Peixoto',
    number: '420',
    neighborhood: 'Centro',
    city: 'Nova Iguaçu',
    state: 'RJ',
    type: 'Consignação',
    agreedPriceLevel: 'Preço Consignado R$ 6,00',
    visitFrequency: '15 dias',
    status: 'Ativo',
    productsOnSiteCount: 32,
    productsValuation: 192.00,
    receivableBalance: 72.00,
    lastVisitDate: '2026-07-25',
    nextVisitDate: '2026-08-10', // Today!
    visitStatus: 'Hoje',
    notes: 'Expositor na frente do caixa principal. Ótimo movimento no fim de semana.',
  },
  {
    id: 'cli-2',
    name: 'Bar do João',
    fantasyName: 'Bar e Petiscaria do João',
    document: '98.765.432/0001-10',
    responsible: 'João Silveira',
    phone: '(21) 99123-8899',
    whatsapp: '5521991238899',
    email: 'bardojoao.ni@hotmail.com',
    cep: '26250-100',
    street: 'Rua Marechal Floriano Peixoto',
    number: '1250',
    neighborhood: 'Alto da Posse',
    city: 'Nova Iguaçu',
    state: 'RJ',
    type: 'Consignação',
    agreedPriceLevel: 'Preço Consignado R$ 6,00',
    visitFrequency: '15 dias',
    status: 'Ativo',
    productsOnSiteCount: 48,
    productsValuation: 288.00,
    receivableBalance: 110.00,
    lastVisitDate: '2026-07-30',
    nextVisitDate: '2026-08-11',
    visitStatus: 'Em breve',
    notes: 'Pediu para levar mais chaveiros do Flamengo e Cerveja na próxima visita.',
  },
  {
    id: 'cli-3',
    name: 'Adega Imperial',
    fantasyName: 'Adega Imperial 24h',
    document: '45.112.890/0001-33',
    responsible: 'Matheus Lima',
    phone: '(21) 97444-1122',
    whatsapp: '5521974441122',
    email: 'adegaimperial24h@outlook.com',
    cep: '26000-000',
    street: 'Rua Bernardino de Melo',
    number: '880',
    neighborhood: 'K20',
    city: 'Nova Iguaçu',
    state: 'RJ',
    type: 'Consignação',
    agreedPriceLevel: 'Preço Consignado R$ 6,00',
    visitFrequency: '7 dias',
    status: 'Ativo',
    productsOnSiteCount: 65,
    productsValuation: 390.00,
    receivableBalance: 240.00,
    lastVisitDate: '2026-07-20',
    nextVisitDate: '2026-08-05', // Atrasada!
    visitStatus: 'Atrasada',
    notes: 'Visita atrasada. Priorizar ligar antes de passar lá.',
  },
  {
    id: 'cli-4',
    name: 'Conveniência Central',
    fantasyName: 'Posto & Conveniência Central',
    document: '33.998.111/0001-55',
    responsible: 'Renata Vasconcelos',
    phone: '(21) 98111-2233',
    whatsapp: '5521981112233',
    email: 'convenienciacentral@posto.com.br',
    cep: '26220-000',
    street: 'Via Light',
    number: '3100',
    neighborhood: 'Luz',
    city: 'Nova Iguaçu',
    state: 'RJ',
    type: 'Consignação',
    agreedPriceLevel: 'Preço Consignado R$ 6,00',
    visitFrequency: '15 dias',
    status: 'Ativo',
    productsOnSiteCount: 52,
    productsValuation: 312.00,
    receivableBalance: 180.00,
    lastVisitDate: '2026-08-01',
    nextVisitDate: '2026-08-16',
    visitStatus: 'Em breve',
  },
  {
    id: 'cli-5',
    name: 'Empresa ABC',
    fantasyName: 'ABC Soluções Corporativas',
    document: '11.222.333/0001-44',
    responsible: 'Rodrigo Mendonça',
    phone: '(21) 99999-5544',
    whatsapp: '5521999995544',
    email: 'compras@empresaabc.com.br',
    cep: '20040-000',
    street: 'Avenida Rio Branco',
    number: '156',
    complement: 'Sala 1204',
    neighborhood: 'Centro',
    city: 'Rio de Janeiro',
    state: 'RJ',
    type: 'Cliente direto',
    agreedPriceLevel: 'Atacado Corporativo',
    visitFrequency: '30 dias',
    status: 'Ativo',
    productsOnSiteCount: 0,
    productsValuation: 0,
    receivableBalance: 350.00,
    lastVisitDate: '2026-07-15',
    nextVisitDate: '2026-08-15',
    visitStatus: 'Em breve',
    notes: 'Compre chaveiros e brindes corporativos personalizados em lote.',
  },
];

export const INITIAL_CLIENT_INVENTORIES: Record<string, ClientInventoryItem[]> = {
  'cli-1': [
    { productId: 'prod-1', productName: 'Chaveiro Glock', sku: 'F-8456', sentQuantity: 10, soldQuantity: 6, currentQuantity: 4, unitPrice: 6.00, lastMovementDate: '2026-08-10' },
    { productId: 'prod-2', productName: 'Chaveiro Cerveja', sku: 'C-3312', sentQuantity: 15, soldQuantity: 5, currentQuantity: 10, unitPrice: 6.00, lastMovementDate: '2026-08-10' },
    { productId: 'prod-4', productName: 'Chaveiro Carro', sku: 'A-2021', sentQuantity: 15, soldQuantity: 1, currentQuantity: 14, unitPrice: 6.00, lastMovementDate: '2026-08-10' },
    { productId: 'prod-5', productName: 'Chaveiro Controle PS5', sku: 'G-9050', sentQuantity: 8, soldQuantity: 4, currentQuantity: 4, unitPrice: 8.00, lastMovementDate: '2026-08-01' },
  ],
  'cli-2': [
    { productId: 'prod-1', productName: 'Chaveiro Glock', sku: 'F-8456', sentQuantity: 15, soldQuantity: 10, currentQuantity: 5, unitPrice: 6.00, lastMovementDate: '2026-07-30' },
    { productId: 'prod-2', productName: 'Chaveiro Cerveja', sku: 'C-3312', sentQuantity: 20, soldQuantity: 12, currentQuantity: 8, unitPrice: 6.00, lastMovementDate: '2026-07-30' },
    { productId: 'prod-3', productName: 'Chaveiro Flamengo', sku: 'F-1895', sentQuantity: 25, soldQuantity: 18, currentQuantity: 7, unitPrice: 6.00, lastMovementDate: '2026-07-30' },
    { productId: 'prod-4', productName: 'Chaveiro Carro', sku: 'A-2021', sentQuantity: 30, soldQuantity: 2, currentQuantity: 28, unitPrice: 6.00, lastMovementDate: '2026-07-15' },
  ],
};

export const INITIAL_CONSIGNMENTS: Consignment[] = [
  {
    id: 'REM-000041',
    clientId: 'cli-1',
    clientName: 'Depósito Avenida',
    date: '2026-08-10',
    itemsCount: 40,
    totalValue: 240.00,
    status: 'Em andamento',
    lastAuditDate: '2026-08-10',
    items: [
      { productId: 'prod-1', productName: 'Chaveiro Glock', sku: 'F-8456', quantity: 10, unitPrice: 6.00, subtotal: 60.00 },
      { productId: 'prod-2', productName: 'Chaveiro Cerveja', sku: 'C-3312', quantity: 15, unitPrice: 6.00, subtotal: 90.00 },
      { productId: 'prod-4', productName: 'Chaveiro Carro', sku: 'A-2021', quantity: 15, unitPrice: 6.00, subtotal: 90.00 },
    ],
    notes: 'Remessa de reposição semanal.',
  },
  {
    id: 'REM-000040',
    clientId: 'cli-2',
    clientName: 'Bar do João',
    date: '2026-07-30',
    itemsCount: 60,
    totalValue: 360.00,
    status: 'Em andamento',
    lastAuditDate: '2026-07-30',
    items: [
      { productId: 'prod-1', productName: 'Chaveiro Glock', sku: 'F-8456', quantity: 15, unitPrice: 6.00, subtotal: 90.00 },
      { productId: 'prod-2', productName: 'Chaveiro Cerveja', sku: 'C-3312', quantity: 20, unitPrice: 6.00, subtotal: 120.00 },
      { productId: 'prod-3', productName: 'Chaveiro Flamengo', sku: 'F-1895', quantity: 25, unitPrice: 6.00, subtotal: 150.00 },
    ],
  },
];

export const INITIAL_VISITS: Visit[] = [
  {
    id: 'VIS-000052',
    clientId: 'cli-1',
    clientName: 'Depósito Avenida',
    scheduledDate: '2026-08-10',
    timeSlot: '14:00',
    reason: 'Conferência + Reposição',
    productsOnSite: 32,
    lastVisitText: 'há 16 dias',
    status: 'Hoje',
  },
  {
    id: 'VIS-000051',
    clientId: 'cli-2',
    clientName: 'Bar do João',
    scheduledDate: '2026-08-11',
    timeSlot: '11:00',
    reason: 'Conferência de Estoque + Troca de baixo giro',
    productsOnSite: 48,
    lastVisitText: 'há 11 dias',
    status: 'Em breve',
  },
  {
    id: 'VIS-000050',
    clientId: 'cli-3',
    clientName: 'Adega Imperial',
    scheduledDate: '2026-08-05',
    timeSlot: '16:30',
    reason: 'Acerto financeiro e contagem',
    productsOnSite: 65,
    lastVisitText: 'há 21 dias',
    status: 'Atrasada',
  },
];

export const INITIAL_EXCHANGES: ExchangeNote[] = [
  {
    id: 'TRC-000014',
    visitId: 'VIS-000052',
    clientId: 'cli-1',
    clientName: 'Depósito Avenida',
    date: '2026-08-10',
    responsible: 'Nicholas',
    itemsRemoved: [
      { productId: 'prod-4', productName: 'Chaveiro Carro', quantity: 10, reason: 'Baixo giro' }
    ],
    itemsAdded: [
      { productId: 'prod-3', productName: 'Chaveiro Flamengo', quantity: 5 },
      { productId: 'prod-2', productName: 'Chaveiro Cerveja', quantity: 5 }
    ],
    notes: 'Substituição de itens sem saída por chaveiros de alta rotatividade.',
  }
];

export const INITIAL_QUOTES: Quote[] = [
  {
    id: 'ORC-000034',
    clientId: 'cli-5',
    clientName: 'Empresa ABC',
    clientDocument: '11.222.333/0001-44',
    clientPhone: '(21) 99999-5544',
    clientAddress: 'Av. Rio Branco, 156, Sala 1204 - Centro, Rio de Janeiro - RJ',
    date: '2026-08-10',
    validityDays: 7,
    productionSlaDays: 5,
    items: [
      { productId: 'prod-1', description: '100x Chaveiro Personalizado com Logo Corporativa', quantity: 100, unitPrice: 5.50, subtotal: 550.00 },
      { productId: 'prod-6', description: '5x Porta Chaves Personalizado de Mesa em PLA', quantity: 5, unitPrice: 35.00, subtotal: 175.00 },
    ],
    subtotal: 725.00,
    discount: 25.00,
    total: 700.00,
    paymentTerms: '50% para início da produção e 50% na entrega.',
    notes: 'Incluso personalização em relevo com arquivo STL enviado pelo cliente.',
    status: 'Aguardando aprovação',
  },
  {
    id: 'ORC-000033',
    clientId: 'cli-1',
    clientName: 'Depósito Avenida',
    date: '2026-08-01',
    validityDays: 15,
    productionSlaDays: 3,
    items: [
      { description: 'Expositor Giratório de Balcão para 50 chaveiros', quantity: 1, unitPrice: 180.00, subtotal: 180.00 }
    ],
    subtotal: 180.00,
    discount: 0.00,
    total: 180.00,
    paymentTerms: '100% no faturamento da remessa',
    status: 'Aprovado',
  }
];

export const INITIAL_ORDERS: Order[] = [];

export const INITIAL_MOVEMENTS: InventoryMovement[] = [
  {
    id: 'mov-1',
    timestamp: '10/08/2026 14:02',
    productId: 'prod-1',
    productName: 'Chaveiro Glock',
    quantityDelta: -6,
    type: 'Venda',
    clientName: 'Depósito Avenida',
    referenceCode: 'VIS-000052',
    notes: 'Conferência de consignação na visita',
  },
  {
    id: 'mov-2',
    timestamp: '10/08/2026 14:04',
    productId: 'prod-3',
    productName: 'Chaveiro Flamengo',
    quantityDelta: 5,
    type: 'Reposição',
    clientName: 'Depósito Avenida',
    referenceCode: 'VIS-000052',
    notes: 'Adicionado no expositor do cliente',
  },
  {
    id: 'mov-3',
    timestamp: '10/08/2026 14:04',
    productId: 'prod-4',
    productName: 'Chaveiro Carro',
    quantityDelta: -10,
    type: 'Retirada',
    clientName: 'Depósito Avenida',
    referenceCode: 'TRC-000014',
    notes: 'Retirado por baixo giro',
  },
  {
    id: 'mov-4',
    timestamp: '10/08/2026 08:30',
    productId: 'prod-1',
    productName: 'Chaveiro Glock',
    quantityDelta: 24,
    type: 'Produção',
    notes: 'Lote #108 finalizado no rack Bambu Lab',
  },
];

export const INITIAL_SALES: SaleTransaction[] = [
  {
    id: 'sal-1',
    timestamp: '10/08/2026 14:02',
    clientName: 'Depósito Avenida',
    amount: 72.00,
    receivedAmount: 72.00,
    balance: 0.00,
    paymentMethod: 'PIX',
    status: 'Pago',
    dueDate: '10/08/2026',
    referenceCode: 'VIS-000052',
  },
  {
    id: 'sal-2',
    timestamp: '10/08/2026 10:30',
    clientName: 'Empresa ABC',
    amount: 700.00,
    receivedAmount: 350.00,
    balance: 350.00,
    paymentMethod: 'PIX',
    status: 'Parcial',
    dueDate: '16/08/2026',
    referenceCode: 'PED-000081',
  },
  {
    id: 'sal-3',
    timestamp: '01/08/2026 16:20',
    clientName: 'Adega Imperial',
    amount: 240.00,
    receivedAmount: 0.00,
    balance: 240.00,
    paymentMethod: 'PIX',
    status: 'Atrasado',
    dueDate: '05/08/2026',
    referenceCode: 'VIS-000050',
  },
];

export const INITIAL_SETTINGS: AppSettings = {
  company: {
    fantasyName: 'RN 3D Impressão 3D',
    legalName: 'Nicholas Rocha Nogueira RN 3D LTDA',
    document: '48.910.223/0001-88',
    phone: '(21) 98822-1100',
    whatsapp: '5521988221100',
    email: 'contato@rn3d.com.br',
    address: 'Rua Dr. Thibau, 80 - Sala 302, Centro - Nova Iguaçu / RJ',
  },
  prefixes: {
    order: 'PED',
    quote: 'ORC',
    consignment: 'REM',
    exchange: 'TRC',
    visit: 'VIS',
  },
  quotes: {
    defaultValidityDays: 7,
    defaultTerms: '50% de sinal no aceite do orçamento e 50% no aviso de conclusão dos produtos.',
    footerText: 'Orçamento válido pelo período informado. A RN 3D garante alta precisão e controle de qualidade de acabamento.',
  },
  inventory: {
    defaultMinStock: 10,
  },
  lastBackupTimestamp: '10/08/2026 às 12:34',
};

export const RECENT_ACTIVITIES = [
  {
    id: 'act-1',
    time: '13:42',
    title: 'Venda registrada',
    client: 'Depósito Avenida',
    value: 'R$ 72,00',
    type: 'venda',
  },
  {
    id: 'act-2',
    time: '12:20',
    title: '15 chaveiros adicionados',
    client: 'Bar do João',
    value: null,
    type: 'reposicao',
  },
  {
    id: 'act-3',
    time: 'Ontem',
    title: 'Orçamento ORC-000034 criado',
    client: 'Empresa ABC',
    value: 'R$ 650,00',
    type: 'orcamento',
  },
  {
    id: 'act-4',
    time: 'Ontem 17:10',
    title: 'Troca TRC-000014 registrada',
    client: 'Depósito Avenida',
    value: '10 retirados / 10 adicionados',
    type: 'troca',
  },
];
